// JavaScript Document
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-migrate.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/bootstrap/bootstrap.bundle.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/bootbox/bootbox.all.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery.mask.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-validate/jquery.validate.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-validate/additional-methods.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-validate/localization/messages_pt_BR.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-validate/jquery.validate.defaults.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery.easing.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/jquery/jquery-ui/jquery-ui.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/blockUI.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/core/adminlte.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/overlayScrollbars/jquery.overlayScrollbars.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/core/cassUtil.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/core/menu.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/core/scripts.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="js/funcoes.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" src="plugins/chart.js/Chart.min.js"%3E%3C/script%3E'));
document.write(unescape('%3Cscript type="text/javascript" charset="utf-8" async src="https://www.googletagmanager.com/gtag/js?id=UA-169908160-1"%3E%3C/script%3E'));
